apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment
  labels:
    app: investment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: investment
  template:
    metadata:
      labels:
        app: investment
    spec:
      containers:
        - name: investment
          image: evertonalaauk/investment:1.0.0
          command: ["python", "manage.py", "runserver", "0.0.0.0:5004"]
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: investment-configmap
          readinessProbe:
              httpGet:
                path: /health
                port: 5004
              initialDelaySeconds: 5
              periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /health
                port: 5004
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}
