apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: evertonalaauk/user:2.0.5
          command: ["python", "manage.py", "runserver", "0.0.0.0:5001"]
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: user-configmap
          readinessProbe:
              httpGet:
                path: /
                port: 5001
              initialDelaySeconds: 5
              periodSeconds: 5
          livenessProbe:
              httpGet:
                path: /
                port: 5001
              initialDelaySeconds: 15
              periodSeconds: 20
          resources: {}