version: '3.7'
services:
  user:
    image: evertonalaauk/user:2.0.5
    #build: ./user
    command: python manage.py runserver 0.0.0.0:5001
    environment:
      - SECRET_KEY=&jt&-yx)8pr=@_g0w908kt1hoyq6e#v3xcs)3-j_moab1xsgz(
      - DATABASE_NAME=internet_banking
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=psql_db
    depends_on:
      - psql_db
      - prometheus
      - grafana
    stdin_open: true
    tty: true
    ports:
      - 5001:5001
    networks:
      - internet_banking_network
    volumes:
      - ./user/:/usr/src/app
    container_name: user

  bank_account:
    image: evertonalaauk/bank_account:2.0.7
    #build: ./bank_account
    command: python manage.py runserver 0.0.0.0:5002
    environment:
      - SECRET_KEY=&jt&-yx)8pr=@_g0w908kt1hoyq6e#v3xcs)3-j_moab1xsgz(
      - DATABASE_NAME=internet_banking
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=psql_db
    depends_on:
      - psql_db
    stdin_open: true
    tty: true
    ports:
      - 5002:5002
    networks:
      - internet_banking_network
    volumes:
      - ./bank_account/:/usr/src/app
    container_name: bank_account

  credit_card:
    image: evertonalaauk/credit_card:1.0.3
    #build: ./credit_card
    command: python manage.py runserver 0.0.0.0:5003
    environment:
      - SECRET_KEY=&jt&-yx)8pr=@_g0w908kt1hoyq6e#v3xcs)3-j_moab1xsgz(
      - DATABASE_NAME=internet_banking
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=psql_db
    depends_on:
      - psql_db
    stdin_open: true
    tty: true
    ports:
      - 5003:5003
    networks:
      - internet_banking_network
    volumes:
      - ./credit_card/:/usr/src/app
    container_name: credit_card

  investment:
    image: evertonalaauk/investment:1.0.0
    #build: ./investment
    command: python manage.py runserver 0.0.0.0:5004
    environment:
      - SECRET_KEY=&jt&-yx)8pr=@_g0w908kt1hoyq6e#v3xcs)3-j_moab1xsgz(
      - DATABASE_NAME=internet_banking
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_HOST=psql_db
    depends_on:
      - psql_db
      - redis
    stdin_open: true
    tty: true
    ports:
      - 5004:5004
    networks:
      - internet_banking_network
    volumes:
      - ./investment/:/usr/src/app
    container_name: investment

  psql_db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=internet_banking
    networks:
      - internet_banking_network
    container_name: postgres

  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - internet_banking_network
    container_name: prometheus
    
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=user@gmail.com
      - GF_SECURITY_ADMIN_PASSWORD=secret
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasource.yml
    networks:
      - internet_banking_network
    container_name: grafana

  redis:
    image: redis
    command: redis-server --requirepass ib_redis
    #ports:
    #  - "6379:6379"
    networks:
      - internet_banking_network
    environment: 
      - CACHE_LOCATION=redis://redis:6379/1
      - CACHE_PASSWORD=ib_redis
    container_name: redis

networks:
  internet_banking_network:
    name: internet-banking-network
    driver: bridge
volumes:
  postgres_data:
  prometheus: